Throw exception if invalid filename is provided
WordPress/Requests pull request #379
Opened 2020-03-15 12:38 UTC by datagutten

Throw an exception if an invalid path is provided in the filename option.
Before this change, the script will continue and try to write and close a file pointer which does not exist.

2021-08-13 11:02 UTC, jrfnl commented
@datagutten  Hiya! Sorry for the long wait, but we're finally trying to get through the list of open PRs.

We're currently planning two triage sessions for Requests 2.0 and would like to invite you to join us in one or both of these sessions to talk us through the PR and discuss it.

The triage sessions are currently planned for:
* Friday August 20, 07:00 - 11:00 UTC
* Friday September 3, 07:00 - 11:00 UTC

Would you be available to join us during those times on one of those days ?

2021-08-20 09:31 UTC, schlessera requested changes

2021-08-20 09:31 UTC, schlessera commented on library/Requests/Transport/cURL.php
> +			@$this->stream_handle = fopen($options['filename'], 'wb');
The error silencing should be as limited as possible, so we want ot have it directly in front of the problematic `fopen()` call.
```suggestion
			$this->stream_handle = @fopen($options['filename'], 'wb');
```

2021-08-20 09:31 UTC, schlessera commented on library/Requests/Transport/fsockopen.php
> +			@$download = fopen($options['filename'], 'wb');
```suggestion
			@download = @fopen($options['filename'], 'wb');
```

2021-08-20 09:37 UTC, schlessera requested changes

2021-08-20 09:37 UTC, schlessera commented on library/Requests/Transport/fsockopen.php
> +			if($download===false) {
```suggestion
			if($download === false) {
```

2021-08-20 09:40 UTC, jrfnl commented
* Rebased the PR to make it mergable.
* Added an extra commit with minor tweaks after review.

2021-08-20 15:51 UTC, jrfnl commented
Added a second commit with minor tweaks to the test and adjustment to an existing test to allow for the exception. This should now be good to go.

2021-08-20 18:39 UTC, schlessera approved these changes

2021-08-20 18:39 UTC, merged