Manage "Expect" header with cURL transport
WordPress/Requests pull request #454
Opened 2021-03-12 18:38 UTC by carlalexander

Fixes #453

2021-03-12 18:40 UTC, carlalexander commented
I'm not sure how you prefer to handle the `strlen` calculation since `data` can be an array or a string. I did it inside the `strlen` happy to change it to something else.

2021-03-12 19:28 UTC, jrfnl commented
@carlalexander Thanks for finding this and for the PR!

Do you think this could be covered by unit tests in some way ?

> I'm not sure how you prefer to handle the strlen calculation since data can be an array or a string. I did it inside the strlen happy to change it to something else.

For code readability and comprehension, I'd much prefer it if it would be pulled apart and calculated before the `strlen()`, but that's just me.

Also, for the multi-line comment, you may want to use multi-comment style `/*... */` ;-)

2021-03-12 19:55 UTC, carlalexander commented
Normally, I do multi-line comments that way too. I'm just trying to keep the same coding style as the one below. Happy to switch it to the `/*`.

I can also create a function to get the get the `strlen`.

For testing, I'd like to add tests. I just didn't really see anything for testing cURL code. The cURL transport has 4 tests to check for some thrown exceptions. That's it.

2021-03-12 20:09 UTC, jrfnl commented
> For testing, I'd like to add tests. I just didn't really see anything for testing cURL code.

I see where your confusion comes from. Most of the tests for the cURL code are in the `RequestsTest_Transport_Base` test class which the `RequestsTest_Transport_cURL` test class extends.
The `RequestsTest_Transport_cURL` class only contains the cURL specific tests, so I imagine a test for this cURL specific issue would be best placed in that file.

If you run the tests with `phpunit --testdox --filter RequestsTest_Transport_cURL`, you can see that the cURL class is tested with a lot more tests than just those in the one file.

2021-03-12 20:10 UTC, jrfnl commented
> Normally, I do multi-line comments that way too. I'm just trying to keep the same coding style as the one below. Happy to switch it to the /*.

I hear you. We've cleaned up the code style recently, cleaning up the comments is on the to do list still, ;-)

2021-03-12 20:30 UTC, carlalexander commented
Alright, I'll take a look at adding tests over the weekend. 

I've done another pass and fixed up the comment and moved the `strlen` code to its own method. I added the method at the end because I can't seem to figure out how methods are ordered. Just let me know where you'd like it.

2021-03-14 17:58 UTC, carlalexander commented
Alright, so I've tried to write some tests, but the Heroku application that we run tests against doesn't seem to return the `Expect` header back. I've tried with both an empty header and one with `100-Continue`. 

Is the code for that Heroku application anywhere? Also it could be that Heroku strips the header.

2021-03-15 03:50 UTC, jrfnl commented
@carlalexander I'm not sure at all, but I suspect it might be this repo: https://github.com/rmccue/httpbin

@rmccue Ryan, could you please confirm ? (or point to the real source)

2021-03-15 04:32 UTC, carlalexander commented
Yeah, I'm trying against `https://httpbin.org/headers` and it's not returning the header regardless that its set or not.

2021-03-15 10:23 UTC, schlessera commented
I think the source of the server is this one: https://github.com/RequestsPHP/test-server

2021-03-15 13:07 UTC, rmccue commented
> I think the source of the server is this one: https://github.com/RequestsPHP/test-server

That's the one, yep :)

2021-03-19 12:49 UTC, jrfnl commented
@carlalexander Just checking in - will you have time to update the PR for the tests ? And if so, what timeline are we looking at ?

2021-03-19 17:49 UTC, carlalexander commented
@jrfnl Hoping to sit down and hammer at it some more this weekend. 😄  I haven't looked at it this week.

2021-03-20 18:17 UTC, carlalexander commented
Ok, so I have some tests running, but they only work with @rmccue's server. I'm just running it locally atm. Are there tests that use it? It seems everything uses httpbin.org and it doesn't return the header. 

Another good news is you can clearly see the 1 sec timeout with the tests. So that's great.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/654684/111881316-45868980-8986-11eb-9edd-81da6f754a0a.png">

2021-03-20 20:20 UTC, jrfnl commented
@carlalexander I hope I understood your question correctly, but AFAICS, all tests which use a function call to `httpbin()` to set the address use the custom test server.

Also see #315 for some additional context.

2021-03-20 21:23 UTC, carlalexander commented
Ok, this helped @jrfnl! I tried with `requests-php-tests.herokuapp.com` and it also strips the header. But Travis seems to run the tests against the test server running with the built-in PHP server. So I pushed the tests up and they seem to work on Travis!

2021-03-20 21:39 UTC, jrfnl commented
@carlalexander Awesome! I'll have a more detailed look soon. What about annotating the tests with the performance fix with [`@small`](https://phpunit.readthedocs.io/en/9.5/annotations.html#small) to ensure they fail if the extra second would be added ?

2021-03-20 21:42 UTC, jrfnl commented
@carlalexander Was just looking at Travis and I notice there does still seem to be an issue:
```
1) RequestsTest_Transport_cURL::testGETWithNestedData

Array to string conversion

/home/travis/build/WordPress/Requests/library/Requests/Transport/cURL.php:573
/home/travis/build/WordPress/Requests/library/Requests/Transport/cURL.php:332
/home/travis/build/WordPress/Requests/library/Requests/Transport/cURL.php:135
/home/travis/build/WordPress/Requests/library/Requests.php:381
/home/travis/build/WordPress/Requests/tests/Transport/Base.php:111

2) RequestsTest_Transport_cURL::testPOSTWithNestedData

Array to string conversion

/home/travis/build/WordPress/Requests/library/Requests/Transport/cURL.php:573
/home/travis/build/WordPress/Requests/library/Requests/Transport/cURL.php:332
/home/travis/build/WordPress/Requests/library/Requests/Transport/cURL.php:135
/home/travis/build/WordPress/Requests/library/Requests.php:381
/home/travis/build/WordPress/Requests/library/Requests.php:270
/home/travis/build/WordPress/Requests/tests/Transport/Base.php:222
```

2021-03-20 21:47 UTC, carlalexander commented
@jrfnl That's my bad. I was using the new function signature for `implode`. Fixed it. Also added `@small` tags.

2021-03-20 21:50 UTC, carlalexander commented
Ok, well the old signature makes `phpcs` fail now lol

2021-03-20 21:58 UTC, jrfnl commented
> using the new function signature for implode.

There is no "new" function signature. There is a cross-version compatible signature and a second signature which was previously supported, but isn't anymore.

The function should be called like so: `implode ( string $separator , array $array )`

> Ok, well the old signature makes phpcs fail now lol

And rightfully so as using the reverse order will throw a deprecation notice on PHP 7.4 (and fail the tests because of it) and be a fatal error on PHP 8.0.

2021-03-20 22:07 UTC, carlalexander commented
Yeah, I'm reverting the change. I understand what's going on now. I'm also going to add some more tests.

2021-03-20 22:17 UTC, jrfnl commented
@carlalexander Appreciated! You're a ⭐

2021-03-20 22:55 UTC, carlalexander commented
Everything is green except for PHP 8.0. It doesn't seem to be an issue with the tests or code. It seems to be PHPUnit related.

2021-03-20 22:58 UTC, jrfnl commented
> Everything is green except for PHP 8.0. It doesn't seem to be an issue with the tests or code. It seems to be PHPUnit related.

Correct - see #439

2021-03-20 23:07 UTC, carlalexander commented
Perfect, should be good to merge once you've done your review. Let me know if you need anything else 😄

2021-03-23 13:17 UTC, schlessera requested changes

2021-03-23 13:17 UTC, schlessera commented on library/Requests/Transport/cURL.php
> +		return strlen($data) >= 1048576 ? '100-Continue' : '';
This is not very efficient given we're only interested in the byte size of the array. The concatenation of the string can be expensive in terms of memory operations, and then you still haven't counted the bytes yet.

How about this instead:
```suggestion
		if (is_array($data)) {
			$iterator = new RecursiveIteratorIterator(new RecursiveArrayIterator($data));
			$bytesize = 0;

			foreach ($iterator as $datum) {
				$bytesize += strlen((string)$datum);
			}
		} else {
			$bytesize = strlen((string)$data);
		}

		return $bytesize >= 1048576 ? '100-Continue' : '';
```

2021-03-27 20:04 UTC, carlalexander commented
Pushed @schlessera's recommended changes 😄

2021-03-28 01:58 UTC, TimothyBJacobs commented on library/Requests/Transport/cURL.php
> +				$bytesize += strlen((string) $datum);
I think it might be worth bailing out here immediately once the `bytesize` limit is reached.

2021-03-28 16:28 UTC, carlalexander commented
Really great suggestion @TimothyBJacobs! I've reworked the function to early return if we hit the 1MB limit.

2021-04-16 17:06 UTC, closed without merging

2021-04-16 17:15 UTC, schlessera commented
Dammit! I broke the PR when I wanted to do a rebase. When will I learn not to touch PRs that were done directly in `master`?

@carlalexander Are you able to push the change again rebased on latest `master`? If not, let me know, and I'll recreate your PR.

2021-04-16 17:31 UTC, schlessera commented
I recreated the PR here: #469